name: Java Runner

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Java file name"
        required: true
      inputdata:
        description: "stdin input"
        required: false
      args:
        description: "command line args"
        required: false
      run_id:
        description: "unique id"
        required: true

permissions:
  contents: write
  actions: write

jobs:
  run-java:
    runs-on: ubuntu-latest
