name: Java Runner

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Java file"
        required: true
      inputdata:
        description: "stdin"
        required: false
      args:
        description: "args"
        required: false
      run_id:
        description: "unique id"
        required: true

# VERY IMPORTANT (without this push will fail)
permissions:
  contents: write
  actions: write

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ---------- COMPILE ----------
      - name: Compile
        run: |
          cd programs
          javac "${{ github.event.inputs.filename }}"

      # ---------- RUN ----------
      - name: Execute
        run: |
          cd programs
          CLASS=$(basename "${{ github.event.inputs.filename }}" .java)

          # create stdin
          echo "${{ github.event.inputs.inputdata }}" > input.txt

          # run program
          timeout 15s java $CLASS ${{ github.event.inputs.args }} < input.txt > output.txt 2>&1 || echo "Runtime error / timeout" >> output.txt

      # ---------- SAVE OUTPUT ----------
      - name: Save output
        run: |
          mkdir -p outputs
          cp programs/output.txt outputs/${{ github.event.inputs.run_id }}.txt

      # ---------- PUSH OUTPUT (THE MAGIC STEP) ----------
      - name: Push output back to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add outputs/

          git commit -m "run ${{ github.event.inputs.run_id }}" || echo "nothing"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
